version: '3'

services:

  #MySQL
  db:
    container_name: db
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sandbox
      MYSQL_USER: sandbox_user
      MYSQL_PASSWORD: sand_boxpass
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3306:3306'
    volumes:
      - './docker/db/data:/var/lib/mysql'
      - './docker/db/my.cnf:/etc/mysql/conf.d/my.cnf'
      - './docker/db/sql:/docker-entrypoint-initdb.d'
    networks:
      - network1
  
  app:
    build:
      context: ./etl
    #container_name: etl
    #image: etl
    depends_on:
      - "db"
    networks:
      - network1
    links:
      - "db"

networks:
    network1:

    